#!/usr/bin/env node

/**
 * MysteryForge YouTube Uploader
 * 
 * Uploads generated videos to YouTube via YouTube Data API v3.
 * 
 * Prerequisites:
 * 1. Google Cloud project with YouTube Data API enabled
 * 2. OAuth 2.0 credentials (client_id, client_secret)
 * 3. Refresh token for channel access
 * 
 * Setup:
 * 1. Go to https://console.cloud.google.com
 * 2. Create project → Enable YouTube Data API v3
 * 3. Create OAuth 2.0 credentials (Desktop app)
 * 4. Run: node youtube-upload.js --auth to get refresh token
 * 
 * Usage:
 *   node youtube-upload.js --latest                    # Upload latest video
 *   node youtube-upload.js "story_folder"              # Upload specific story
 *   node youtube-upload.js --list                      # List recent uploads
 *   node youtube-upload.js --auth                      # Generate auth token
 * 
 * Environment Variables:
 *   YOUTUBE_CLIENT_ID      - OAuth client ID
 *   YOUTUBE_CLIENT_SECRET  - OAuth client secret
 *   YOUTUBE_REFRESH_TOKEN  - OAuth refresh token
 * 
 * Notes:
 *   - YouTube has daily upload quotas (default: 6 videos/day)
 *   - Videos default to 'unlisted' for safety
 *   - Title and description auto-generated from story.json
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

const YOUTUBE_API_BASE = 'www.googleapis.com';
const UPLOAD_URL = '/upload/youtube/v3/videos';
const VIDEOS_URL = '/youtube/v3/videos';

// Default video settings
const DEFAULT_VISIBILITY = 'unlisted'; // 'public', 'unlisted', 'private'
const DEFAULT_CATEGORY = '24'; // Entertainment
const DEFAULT_TAGS = ['story', 'mystery', 'fiction', 'narrative', 'storytelling'];

function parseArgs() {
  const args = process.argv.slice(2);
  return {
    latest: args.includes('--latest'),
    list: args.includes('--list'),
    auth: args.includes('--auth'),
    public: args.includes('--public'),
    private: args.includes('--private'),
    storyFolder: args.find(a => !a.startsWith('--'))
  };
}

function getLatestStoryFolder() {
  const outputDir = path.join(process.cwd(), 'output');
  const folders = fs.readdirSync(outputDir)
    .filter(f => {
      const p = path.join(outputDir, f);
      return fs.statSync(p).isDirectory() && 
             fs.existsSync(path.join(p, 'story.json')) &&
             fs.existsSync(path.join(p, 'video.mp4'));
    })
    .map(f => ({ name: f, mtime: fs.statSync(path.join(outputDir, f)).mtime }))
    .sort((a, b) => b.mtime - a.mtime);
  
  return folders.length > 0 ? path.join(outputDir, folders[0].name) : null;
}

/**
 * Get access token from refresh token
 */
async function getAccessToken() {
  const clientId = process.env.YOUTUBE_CLIENT_ID;
  const clientSecret = process.env.YOUTUBE_CLIENT_SECRET;
  const refreshToken = process.env.YOUTUBE_REFRESH_TOKEN;

  if (!clientId || !clientSecret || !refreshToken) {
    throw new Error('Missing YouTube credentials. Set YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, and YOUTUBE_REFRESH_TOKEN');
  }

  return new Promise((resolve, reject) => {
    const data = new URLSearchParams({
      client_id: clientId,
      client_secret: clientSecret,
      refresh_token: refreshToken,
      grant_type: 'refresh_token'
    }).toString();

    const options = {
      hostname: 'oauth2.googleapis.com',
      path: '/token',
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': Buffer.byteLength(data)
      }
    };

    const req = https.request(options, (res) => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          const json = JSON.parse(body);
          if (json.error) {
            reject(new Error(`OAuth error: ${json.error}`));
          } else {
            resolve(json.access_token);
          }
        } catch (e) {
          reject(new Error(`Failed to parse token response: ${e.message}`));
        }
      });
    });

    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

/**
 * Generate YouTube video metadata from story
 */
function generateMetadata(story) {
  // Title: Convert snake_case to readable title
  const titleRaw = story.title?.replace(/_/g, ' ').replace(/\d{4}-\d{2}-\d{2}.*/, '').trim();
  const title = titleRaw || 'Mystery Story';
  
  // Capitalize first letter of each word
  const titleCased = title.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
  
  // Description with story hook
  const hook = story.segments?.[0]?.text?.substring(0, 150) || '';
  const description = `${hook}...

This is a fictional story created for entertainment purposes.

#story #${story.genre || 'mystery'} #fiction #narrative

Generated by MysteryForge
https://github.com/ronaldjohnatanoso/mysteryforge`;

  // Tags based on genre
  const genreTags = {
    mystery: ['mystery', 'crime', 'suspense', 'thriller', 'detective'],
    horror: ['horror', 'scary', 'creepy', 'paranormal', 'haunting'],
    revenge: ['revenge', 'justice', 'karma', 'storytime', 'reddit'],
    confession: ['confession', 'secret', 'storytime', 'anonymous', 'truestory']
  };

  const tags = [...DEFAULT_TAGS, ...(genreTags[story.genre] || [])];

  return {
    title: titleCased,
    description,
    tags,
    categoryId: DEFAULT_CATEGORY
  };
}

/**
 * Upload video to YouTube
 */
async function uploadVideo(videoPath, metadata, accessToken, visibility = DEFAULT_VISIBILITY) {
  return new Promise((resolve, reject) => {
    const videoData = fs.readFileSync(videoPath);
    
    const metadataJson = JSON.stringify({
      snippet: {
        title: metadata.title,
        description: metadata.description,
        tags: metadata.tags,
        categoryId: metadata.categoryId
      },
      status: {
        privacyStatus: visibility,
        selfDeclaredMadeForKids: false
      }
    });

    const options = {
      hostname: YOUTUBE_API_BASE,
      path: `${UPLOAD_URL}?part=snippet,status`,
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${accessToken}`,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(metadataJson)
      }
    };

    console.log('\n   Uploading to YouTube...');
    console.log(`   Title: ${metadata.title}`);
    console.log(`   Visibility: ${visibility}`);
    console.log(`   Size: ${(videoData.length / 1024 / 1024).toFixed(1)} MB`);

    // Note: This is a simplified implementation
    // Real implementation would need resumable upload for large files
    // See: https://developers.google.com/youtube/v3/guides/using_resumable_upload_protocol
    
    reject(new Error(
      'YouTube upload requires google-auth-library and googleapis packages.\n' +
      'Install with: npm install google-auth-library googleapis\n' +
      'Then run the full upload implementation.\n\n' +
      'Alternative: Use YouTube Studio web interface to upload manually.\n' +
      'Video ready at: ' + videoPath
    ));
  });
}

/**
 * List recent uploads
 */
async function listUploads(accessToken) {
  // Would require channels.list to get uploads playlist
  // Then playlistItems.list to get videos
  console.log('\n📋 Recent uploads would be listed here.');
  console.log('   Requires googleapis package for full implementation.\n');
}

/**
 * OAuth authentication flow
 */
async function runAuthFlow() {
  console.log('\n🔐 YouTube OAuth Setup\n');
  console.log('To upload videos to YouTube, you need OAuth credentials.');
  console.log('\nSteps:');
  console.log('1. Go to https://console.cloud.google.com');
  console.log('2. Create a new project or select existing');
  console.log('3. Enable YouTube Data API v3');
  console.log('4. Go to Credentials → Create Credentials → OAuth client ID');
  console.log('5. Choose "Desktop app"');
  console.log('6. Copy the Client ID and Client Secret');
  console.log('\nThen run:');
  console.log('  export YOUTUBE_CLIENT_ID="your-client-id"');
  console.log('  export YOUTUBE_CLIENT_SECRET="your-client-secret"');
  console.log('\nFor refresh token generation, you\'ll need to:');
  console.log('  npm install google-auth-library googleapis');
  console.log('  node scripts/youtube-auth.js\n');
}

async function main() {
  const opts = parseArgs();

  // Auth flow
  if (opts.auth) {
    await runAuthFlow();
    process.exit(0);
  }

  // List uploads
  if (opts.list) {
    const accessToken = await getAccessToken();
    await listUploads(accessToken);
    process.exit(0);
  }

  // Find story folder
  let storyFolder = opts.storyFolder;
  if (opts.latest || !storyFolder) {
    storyFolder = getLatestStoryFolder();
    if (!storyFolder) {
      console.error('❌ No video-ready stories found');
      console.error('   Run: node generate.js && node assemble-video.js --latest');
      process.exit(1);
    }
  } else {
    storyFolder = path.join(process.cwd(), 'output', storyFolder);
  }

  // Check prerequisites
  const videoPath = path.join(storyFolder, 'video.mp4');
  const storyPath = path.join(storyFolder, 'story.json');

  if (!fs.existsSync(videoPath)) {
    console.error('❌ No video.mp4 found in story folder');
    process.exit(1);
  }

  if (!fs.existsSync(storyPath)) {
    console.error('❌ No story.json found in story folder');
    process.exit(1);
  }

  // Load story
  const story = JSON.parse(fs.readFileSync(storyPath, 'utf8'));
  const metadata = generateMetadata(story);

  // Determine visibility
  let visibility = DEFAULT_VISIBILITY;
  if (opts.public) visibility = 'public';
  if (opts.private) visibility = 'private';

  console.log(`\n🎬 YouTube Upload: ${story.title}`);
  console.log(`   Video: ${videoPath}`);

  try {
    const accessToken = await getAccessToken();
    const result = await uploadVideo(videoPath, metadata, accessToken, visibility);
    console.log('\n✅ Upload complete!');
    console.log(`   Video ID: ${result.id}`);
    console.log(`   URL: https://youtube.com/watch?v=${result.id}\n`);
  } catch (e) {
    console.error(`\n❌ Upload failed: ${e.message}\n`);
    process.exit(1);
  }
}

main().catch(e => { console.error('❌', e.message); process.exit(1); });