#!/bin/bash
# Daily commit script for MysteryForge
# Generates content, commits, and pushes to keep GitHub green

set -e

cd /home/ronald/projects/mysteryforge

# Load credentials
source /home/ronald/credentials/.env
export CEREBRAS_API_KEY GROQ_API_KEY PEXELS_API_KEY

# Choose a random genre and structure
GENRES=("mystery" "crime" "paranormal" "thriller")
STRUCTURES=("whodunit" "found-footage" "unsolved-twist" "anthology")

GENRE=${GENRES[$RANDOM % ${#GENRES[@]}]}
STRUCTURE=${STRUCTURES[$RANDOM % ${#STRUCTURES[@]}]}

echo "🔨 Generating $GENRE story with $STRUCTURE structure..."

# Generate a new story
node generate.js --genre "$GENRE" --length 3 --structure "$STRUCTURE" --provider cerebras

# Count total stories
STORY_COUNT=$(ls -1 output/scripts/*.md 2>/dev/null | wc -l)

# Update README with stats
sed -i "s/Stories generated:.*/Stories generated: $STORY_COUNT/" README.md 2>/dev/null || true

# Commit and push
git add -A
git commit -m "Generate $GENRE story ($STRUCTURE)

Auto-generated by Hephaestus ⚒️
Total stories: $STORY_COUNT" --allow-empty

git push origin main

echo "✅ Committed and pushed!"